language: go
sudo: required
dist: trusty

go:
  - 1.6.x
  - 1.7.x
  - tip

env:
  global:
    - TOOLS_CMD=golang.org/x/tools/cmd
    - PATH=$GOROOT/bin:$PATH
    - GO15VENDOREXPERIMENT=1
  matrix:
   - TARGET=amd64
   - TARGET=arm
   - TARGET=arm64
   - TARGET=ppc64le

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  exclude:
    - go: tip
      env: arm
    - go: tip
      env: arm64
    - go: tip
      env: ppc64le

install:
 - go get ${TOOLS_CMD}/cover
 - go get github.com/modocache/gover
 - go get github.com/mattn/goveralls
# Travis-Ci is running a vintage kernel image.
# We need to patch ipvlan driver for functional tests to work.
 - sudo apt-get -y install linux-headers-`uname -r`
 - apt-get source linux-lts-vivid
 - cd linux-lts-vivid-3.19.0; make oldconfig;make prepare;make scripts
 - cd drivers/net/ipvlan; wget -O - https://github.com/torvalds/linux/commit/f631c44bbe1581d18d0aba628b3802d0eacb6373.patch|patch -p4
 - make -C /usr/src/linux-headers-`uname -r` M=$(pwd) modules
 - sudo insmod ipvlan.ko
 - cd ../../../../
 - sudo apt-get -y install isc-dhcp-server radvd

script:
 - >
    if [ "${TARGET}" == "amd64" ]; then
      GOARCH="${TARGET}" ./test;
    else
      GOARCH="${TARGET}" ./build;
    fi

notifications:
  email: false

git:
  depth: 9999999
